
-- Supabase Schema for AI Training Control Center
-- IMPORTANT: Run this entire script in your Supabase SQL Editor

-- 1. Create Tables
CREATE TABLE IF NOT EXISTS tunnels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS game_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  initial_player_balance FLOAT8 NOT NULL DEFAULT 1000.0,
  bet_amount FLOAT8 NOT NULL DEFAULT 10.0,
  counter_fee FLOAT8 NOT NULL DEFAULT 5.0,
  win_payout FLOAT8 NOT NULL DEFAULT 10.0,
  counter_win_payout FLOAT8 NOT NULL DEFAULT 25.0,
  dealer_stand INT4 NOT NULL DEFAULT 17,
  total_timesteps BIGINT NOT NULL DEFAULT 1000000,
  max_balance_ref FLOAT8 DEFAULT 2000.0,
  refill_penalty FLOAT8 DEFAULT -50.0
);

CREATE TABLE IF NOT EXISTS training_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  step BIGINT NOT NULL,
  house_profit FLOAT8 NOT NULL,
  player_money FLOAT8 NOT NULL,
  win_rate FLOAT4 NOT NULL,
  counter_usage FLOAT4 NOT NULL,
  refill_count INT4 NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS system_commands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  command TEXT NOT NULL,
  payload JSONB DEFAULT '{}',
  processed BOOLEAN DEFAULT FALSE
);

-- 2. Enable RLS on all tables
ALTER TABLE tunnels ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE training_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_commands ENABLE ROW LEVEL SECURITY;

-- 3. Create Public Access Policies (Allows web app to function with anon key)
-- NOTE: In a production app, you would restrict these, but for an AI training lab, we allow all.

DROP POLICY IF EXISTS "Public Select" ON tunnels;
CREATE POLICY "Public Select" ON tunnels FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public Insert" ON tunnels;
CREATE POLICY "Public Insert" ON tunnels FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Select" ON game_configs;
CREATE POLICY "Public Select" ON game_configs FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public Insert" ON game_configs;
CREATE POLICY "Public Insert" ON game_configs FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Select" ON training_logs;
CREATE POLICY "Public Select" ON training_logs FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public Insert" ON training_logs;
CREATE POLICY "Public Insert" ON training_logs FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public All" ON system_commands;
CREATE POLICY "Public All" ON system_commands FOR ALL USING (true);
